// <auto-generated />
using System;
using CollectionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CollectionService.Infrastructure.Migrations
{
    [DbContext(typeof(CollectionDbContext))]
    partial class CollectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collection")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionConfirmation", b =>
                {
                    b.Property<int>("ConfirmationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("confirmation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfirmationId"));

                    b.Property<string>("AfterImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("after_image_url");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<string>("BeforeImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("before_image_url");

                    b.Property<DateTime?>("ConfirmedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.HasKey("ConfirmationId")
                        .HasName("collection_confirmations_pkey");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("collection_confirmations", "collection");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetailId"));

                    b.Property<double>("ActualWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_weight");

                    b.Property<int>("ConfirmationId")
                        .HasColumnType("integer")
                        .HasColumnName("confirmation_id");

                    b.Property<int>("WasteTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("waste_type_id");

                    b.HasKey("DetailId")
                        .HasName("collection_details_pkey");

                    b.HasIndex("ConfirmationId");

                    b.ToTable("collection_details", "collection");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("IssueImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("issue_image_url");

                    b.Property<string>("IssueReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("issue_reason");

                    b.Property<string>("IssueReport")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("issue_report");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("RequestId")
                        .HasName("collection_requests_pkey");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("collection_requests", "collection");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectorAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrived_at");

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.Property<int>("AssignedCollector")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_collector");

                    b.Property<string>("BeforeImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("before_image_url");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Assigned")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId")
                        .HasName("collector_assignments_pkey");

                    b.HasIndex("RequestId");

                    b.ToTable("collector_assignments", "collection");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionConfirmation", b =>
                {
                    b.HasOne("CollectionService.Domain.Entities.CollectorAssignment", "Assignment")
                        .WithOne("CollectionConfirmation")
                        .HasForeignKey("CollectionService.Domain.Entities.CollectionConfirmation", "AssignmentId")
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionDetail", b =>
                {
                    b.HasOne("CollectionService.Domain.Entities.CollectionConfirmation", "Confirmation")
                        .WithMany("CollectionDetails")
                        .HasForeignKey("ConfirmationId")
                        .IsRequired();

                    b.Navigation("Confirmation");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectorAssignment", b =>
                {
                    b.HasOne("CollectionService.Domain.Entities.CollectionRequest", "Request")
                        .WithMany("CollectorAssignments")
                        .HasForeignKey("RequestId")
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionConfirmation", b =>
                {
                    b.Navigation("CollectionDetails");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectionRequest", b =>
                {
                    b.Navigation("CollectorAssignments");
                });

            modelBuilder.Entity("CollectionService.Domain.Entities.CollectorAssignment", b =>
                {
                    b.Navigation("CollectionConfirmation");
                });
#pragma warning restore 612, 618
        }
    }
}
