class Languages {
  static const Map<String, String> en = {
    'app_name': 'EcoCollect',
    'lang_vi': '🇻🇳 Tiếng Việt',
    'lang_en': '🇬🇧 English',
    'loading': 'Loading...',
    'guest': 'Guest',
    'points_unit': 'pts',
    'home': 'Home',
    'create_report': 'Create Report',
    'rewards': 'Rewards',
    'history': 'History',
    'total_points': 'Total Points',
    'points_subtitle': 'Lifetime points',
    'reports_submitted': 'Reports',
    'reports_subtitle': 'Submitted requests',
    'reward_events': 'Events',
    'events_subtitle': 'Participated',
    'active_requests': 'Active Requests',
    'no_active_reports': 'No active reports',
    'recent_activity': 'Recent Activity',
    'no_activity_yet': 'No activity yet',
    'report_title': 'Create Waste Report',
    'report_subtitle': 'Take a photo & select a location on the map',
    'submit_report': 'Submit Report',
    'upload_photo': 'Upload Waste Photo',
    'drag_drop_hint': 'Drag & drop an image here or click to select',
    'supported_formats': 'Supported: PNG, JPG, JPEG (Max 10MB)',
    'waste_types_label': 'Waste Types * (You can select multiple)',
    'waste_plastic': 'Plastic',
    'waste_paper': 'Paper',
    'waste_metal': 'Metal',
    'waste_glass': 'Glass',
    'waste_ewaste': 'E-Waste',
    'detailed_description': 'Detailed Description',
    'description_hint': 'Add detailed information about the waste (optional)...',
    'collection_location': 'Collection Location',
    'address_hint': 'Eg: 123 Main St, Ho Chi Minh City...',
    'search': 'Search',
    'use_current_location': 'Use Current Location',
    'latitude_label': 'Latitude (Lat):',
    'longitude_label': 'Longitude (Lng):',
    'not_selected': 'Not selected',
    'banner_title': 'Together for a Greener Future',
    'banner_subtitle':
    'Join us in making a difference. Report waste, track collection, and help create a cleaner environment for everyone.',
    'stat_users': 'Active Users',
    'stat_recycled': 'Waste Recycled',
    'stat_satisfaction': 'Satisfaction',
    'welcome_back': 'Welcome back',
    'sign_in_subtitle': 'Sign in to your account to continue your eco journey',
    'email': 'Email',
    'email_hint': 'name@example.com',
    'err_email_required': 'Please enter your email',
    'err_email_invalid': 'Please enter a valid email address',
    'password': 'Password',
    'forgot_password': 'Forgot password?',
    'password_hint': 'Enter your password',
    'err_password_required': 'Please enter your password',
    'log_in': 'Log In',
    'no_account': "Don't have an account?",
    'sign_up': 'Sign Up',
    'create_account': 'Create an account',
    'join_community': 'Join our eco-friendly community',
    'full_name': 'Full Name',
    'name_hint': 'John Doe',
    'err_name_required': 'Please enter your full name',
    'confirm_password': 'Confirm Password',
    'confirm_password_hint': 'Confirm your password',
    'err_confirm_required': 'Please confirm your password',
    'err_password_mismatch': 'Passwords do not match',
    'err_password_min_length': 'Password must be at least 8 characters',
    'err_password_lowercase': 'Password must contain at least one lowercase letter',
    'err_password_number': 'Password must contain at least one number',
    'err_password_special': 'Password must contain at least one special character',
    'send_otp': 'Send OTP',
    'already_have_account': 'Already have an account?',
    'sign_in': 'Sign In',
    'verify_email': 'Verify Email',
    'verify_email_subtitle': 'Enter the OTP sent to your email',
    'otp_sent_to': 'An OTP has been sent to:',
    'enter_otp_code': 'Enter OTP Code',
    'didnt_receive': "Didn't receive the code? ",
    'resend_otp': 'Resend OTP',
    'resend_in': 'Resend in {time}',
    'verify_otp': 'Verify OTP',
    'go_back': 'Go Back',
  };

  static const Map<String, String> vi = {
    'app_name': 'EcoCollect',
    'lang_vi': '🇻🇳 Tiếng Việt',
    'lang_en': '🇬🇧 English',
    'loading': 'Đang tải...',
    'guest': 'Khách',
    'points_unit': 'điểm',
    'home': 'Trang chủ',
    'create_report': 'Tạo báo cáo',
    'rewards': 'Phần thưởng',
    'history': 'Lịch sử',
    'total_points': 'Tổng điểm',
    'points_subtitle': 'Điểm tích lũy',
    'reports_submitted': 'Báo cáo',
    'reports_subtitle': 'Đã gửi',
    'reward_events': 'Sự kiện',
    'events_subtitle': 'Đã tham gia',
    'active_requests': 'Yêu cầu đang xử lý',
    'no_active_reports': 'Chưa có báo cáo nào',
    'recent_activity': 'Hoạt động gần đây',
    'no_activity_yet': 'Chưa có hoạt động nào',
    'report_title': 'Tạo báo cáo rác thải',
    'report_subtitle': 'Chụp ảnh và chọn vị trí trên bản đồ',
    'submit_report': 'Gửi báo cáo',
    'upload_photo': 'Tải ảnh rác thải',
    'drag_drop_hint': 'Kéo thả ảnh vào đây hoặc bấm để chọn',
    'supported_formats': 'Hỗ trợ: PNG, JPG, JPEG (Tối đa 10MB)',
    'waste_types_label': 'Loại rác * (Có thể chọn nhiều)',
    'waste_plastic': 'Nhựa',
    'waste_paper': 'Giấy',
    'waste_metal': 'Kim loại',
    'waste_glass': 'Thủy tinh',
    'waste_ewaste': 'Rác điện tử',
    'detailed_description': 'Mô tả chi tiết',
    'description_hint': 'Thêm thông tin chi tiết về rác thải (không bắt buộc)...',
    'collection_location': 'Vị trí thu gom',
    'address_hint': 'VD: 123 Đường ABC, TP. Hồ Chí Minh...',
    'search': 'Tìm kiếm',
    'use_current_location': 'Dùng vị trí hiện tại',
    'latitude_label': 'Vĩ độ (Lat):',
    'longitude_label': 'Kinh độ (Lng):',
    'not_selected': 'Chưa chọn',
    'banner_title': 'Cùng nhau vì một tương lai xanh hơn',
    'banner_subtitle':
    'Hãy cùng chúng tôi tạo nên sự khác biệt. Báo cáo rác thải, theo dõi thu gom và góp phần xây dựng môi trường sạch hơn cho mọi người.',
    'stat_users': 'Người dùng',
    'stat_recycled': 'Rác tái chế',
    'stat_satisfaction': 'Hài lòng',
    'welcome_back': 'Chào mừng trở lại',
    'sign_in_subtitle': 'Đăng nhập để tiếp tục hành trình sống xanh của bạn',
    'email': 'Email',
    'email_hint': 'ten@example.com',
    'err_email_required': 'Vui lòng nhập email',
    'err_email_invalid': 'Vui lòng nhập địa chỉ email hợp lệ',
    'password': 'Mật khẩu',
    'forgot_password': 'Quên mật khẩu?',
    'password_hint': 'Nhập mật khẩu',
    'err_password_required': 'Vui lòng nhập mật khẩu',
    'log_in': 'Đăng nhập',
    'no_account': 'Chưa có tài khoản?',
    'sign_up': 'Đăng ký',
    'create_account': 'Tạo tài khoản',
    'join_community': 'Tham gia cộng đồng sống xanh',
    'full_name': 'Họ và tên',
    'name_hint': 'Nguyễn Văn A',
    'err_name_required': 'Vui lòng nhập họ và tên',
    'confirm_password': 'Xác nhận mật khẩu',
    'confirm_password_hint': 'Nhập lại mật khẩu',
    'err_confirm_required': 'Vui lòng xác nhận mật khẩu',
    'err_password_mismatch': 'Mật khẩu không khớp',
    'err_password_min_length': 'Mật khẩu phải có ít nhất 8 ký tự',
    'err_password_lowercase': 'Mật khẩu phải có ít nhất một chữ thường',
    'err_password_number': 'Mật khẩu phải có ít nhất một chữ số',
    'err_password_special': 'Mật khẩu phải có ít nhất một ký tự đặc biệt',
    'send_otp': 'Gửi mã OTP',
    'already_have_account': 'Đã có tài khoản?',
    'sign_in': 'Đăng nhập',
    'verify_email': 'Xác minh email',
    'verify_email_subtitle': 'Nhập mã OTP đã gửi đến email của bạn',
    'otp_sent_to': 'Mã OTP đã được gửi đến:',
    'enter_otp_code': 'Nhập mã OTP',
    'didnt_receive': 'Không nhận được mã? ',
    'resend_otp': 'Gửi lại OTP',
    'resend_in': 'Gửi lại sau {time}',
    'verify_otp': 'Xác minh OTP',
    'go_back': 'Quay lại',
  };
}
