// <auto-generated />
using System;
using IdentityService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Domain.Entities.CollectorProfile", b =>
                {
                    b.Property<int>("CollectorId")
                        .HasColumnType("integer")
                        .HasColumnName("collector_id");

                    b.Property<DateTime?>("AvailabilityUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("availability_updated_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterprise_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<int>("WarningCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("warning_count");

                    b.HasKey("CollectorId")
                        .HasName("collector_profiles_pkey");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("collector_profiles", "identity");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.EnterpriseProfile", b =>
                {
                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterprise_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ManagedDistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("managed_district_id");

                    b.HasKey("EnterpriseId")
                        .HasName("enterprise_profiles_pkey");

                    b.ToTable("enterprise_profiles", "identity");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Regular citizen user",
                            RoleName = "Citizen"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Enterprise account",
                            RoleName = "Enterprise"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Waste collector",
                            RoleName = "Collector"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "System administrator",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_points");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.CollectorProfile", b =>
                {
                    b.HasOne("IdentityService.Domain.Entities.User", "Collector")
                        .WithOne("CollectorProfile")
                        .HasForeignKey("IdentityService.Domain.Entities.CollectorProfile", "CollectorId")
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.Entities.EnterpriseProfile", "EnterpriseProfile")
                        .WithMany("CollectorProfiles")
                        .HasForeignKey("EnterpriseId")
                        .IsRequired();

                    b.Navigation("Collector");

                    b.Navigation("EnterpriseProfile");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.EnterpriseProfile", b =>
                {
                    b.HasOne("IdentityService.Domain.Entities.User", "Enterprise")
                        .WithOne("EnterpriseProfile")
                        .HasForeignKey("IdentityService.Domain.Entities.EnterpriseProfile", "EnterpriseId")
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.User", b =>
                {
                    b.HasOne("IdentityService.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.EnterpriseProfile", b =>
                {
                    b.Navigation("CollectorProfiles");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.User", b =>
                {
                    b.Navigation("CollectorProfile");

                    b.Navigation("EnterpriseProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
