// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasteReportService.Infrastructure.Persistence;

#nullable disable

namespace WasteReportService.Infrastructure.Migrations
{
    [DbContext(typeof(WasteReportDbContext))]
    [Migration("20260709233125_AddEstimatedSizeToWasteReports")]
    partial class AddEstimatedSizeToWasteReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("waste")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasteReportService.Domain.Entities.AiWastePrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prediction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PredictionId"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<string>("SuggestedType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("suggested_type");

                    b.HasKey("PredictionId")
                        .HasName("ai_waste_predictions_pkey");

                    b.HasIndex("ReportId");

                    b.ToTable("ai_waste_predictions", "waste");
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("DistrictId")
                        .HasName("districts_pkey");

                    b.ToTable("districts", "waste");
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.WasteReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<string>("EstimatedSize")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estimated_size");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("integer")
                        .HasColumnName("submitted_by");

                    b.HasKey("ReportId")
                        .HasName("waste_reports_pkey");

                    b.HasIndex("DistrictId");

                    b.ToTable("waste_reports", "waste");
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.WasteType", b =>
                {
                    b.Property<int>("WasteTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("waste_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WasteTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reward_points");

                    b.HasKey("WasteTypeId")
                        .HasName("waste_types_pkey");

                    b.ToTable("waste_types", "waste");
                });

            modelBuilder.Entity("report_waste_types", b =>
                {
                    b.Property<int>("report_id")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<int>("waste_type_id")
                        .HasColumnType("integer")
                        .HasColumnName("waste_type_id");

                    b.HasKey("report_id", "waste_type_id");

                    b.HasIndex("waste_type_id");

                    b.ToTable("report_waste_types", "waste");
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.AiWastePrediction", b =>
                {
                    b.HasOne("WasteReportService.Domain.Entities.WasteReport", "Report")
                        .WithMany("AiWastePredictions")
                        .HasForeignKey("ReportId")
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.WasteReport", b =>
                {
                    b.HasOne("WasteReportService.Domain.Entities.District", "District")
                        .WithMany("WasteReports")
                        .HasForeignKey("DistrictId");

                    b.Navigation("District");
                });

            modelBuilder.Entity("report_waste_types", b =>
                {
                    b.HasOne("WasteReportService.Domain.Entities.WasteReport", null)
                        .WithMany()
                        .HasForeignKey("report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteReportService.Domain.Entities.WasteType", null)
                        .WithMany()
                        .HasForeignKey("waste_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.District", b =>
                {
                    b.Navigation("WasteReports");
                });

            modelBuilder.Entity("WasteReportService.Domain.Entities.WasteReport", b =>
                {
                    b.Navigation("AiWastePredictions");
                });
#pragma warning restore 612, 618
        }
    }
}
